services:
  portal_clientes:
    build:
      context: ./portal_clientes
    ports:
      - "8005:80"
    volumes:
      - ./portal_clientes:/var/www/html
      - portal_vendor:/var/www/html/vendor
      - portal_storage:/var/www/html/storage

  portal_admin:
    build:
      context: ./portal_admin
    ports:
      - "5005:5000"
    volumes:
      - ./portal_admin:/app
    environment:
      - FLASK_DEBUG=1

volumes:
  portal_vendor:
  portal_storage:
